#!/usr/bin/env python3
"""Rasterises the FPS counter's glyphs from DarkCloudCompendium.ttf (Dark Cloud Compendium Community
Font by Dayuppy/MoonBunny) into port/src/platform/overlay_font.inc.

    python tools/font/gen_overlay_font.py [size]
"""
import sys
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

here = Path(__file__).parent
size = int(sys.argv[1]) if len(sys.argv) > 1 else 11
font = ImageFont.truetype(str(here / "DarkCloudCompendium.ttf"), size)
chars = " ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.,:;/()+-_%'[]?~"
ascent, descent = font.getmetrics()

out = ["// Generated by tools/font/gen_overlay_font.py; do not edit.",
       f"constexpr int kFontAscent = {ascent};", f"constexpr int kFontHeight = {ascent + descent};", ""]
glyphs = []
for c in chars:
    adv = round(font.getlength(c))
    w = max(adv + 2, 1)
    im = Image.new("L", (w, ascent + descent), 0)
    ImageDraw.Draw(im).text((1, 0), c, font=font, fill=255)
    box = im.getbbox()
    name = f"kBits{ord(c):02X}"
    if box is None:
        glyphs.append((c, adv, 0, 0, 0, 0, "nullptr"))
        continue
    l, t, r, b = box
    data = list(im.crop(box).tobytes())
    out.append(f"constexpr std::uint8_t {name}[] = {{" + ",".join(map(str, data)) + "};")
    glyphs.append((c, adv, l - 1, t, r - l, b - t, name))
out.append("")
out.append("constexpr FontGlyph kFont[] = {")
for c, adv, x, y, w, h, name in glyphs:
    ch = "'" + (chr(92) + "'" if c == "'" else c) + "'"
    out.append(f"    {{{ch}, {adv}, {x}, {y}, {w}, {h}, {name}}},")
out.append("};")
(here.parent.parent / "port/src/platform/overlay_font.inc").write_text("\n".join(out) + "\n")
print("ascent", ascent, "descent", descent, "glyphs", len(glyphs))
